import { writeFile } from 'node:fs/promises';
import { companyFundamentalsDataset } from '../src/data/companyFundamentals';
import { secCompanyReportSources } from '../src/data/companyReportSources.sec';
import { listSecPeriodicFilings, type SecRecentFilings } from '../src/data/companyReportMaintenance';
import { matchCompanyReportSources } from '../src/data/companySourceMatching';
import { fetchSecJson, fetchSecSubmissions, loadSecCikByTicker, secDomesticCompanies } from './lib/sec';

const args = new Set(process.argv.slice(2));
const selected = [...args].find(arg => arg.startsWith('--company='))?.slice(10);
const tickerMap = await loadSecCikByTicker();
const output = { ...secCompanyReportSources };
let failed = false;
for (const company of secDomesticCompanies(companyFundamentalsDataset.companies).filter(item => !selected || item.id === selected)) {
  try {
    const cik = tickerMap.get(company.ticker.toUpperCase());
    if (!cik) throw new Error('SEC ticker not found');
    const submissions = await fetchSecSubmissions(cik);
    const filings = listSecPeriodicFilings(submissions.filings.recent);
    const earliest = [...company.annual, ...company.quarterly].reduce((day, point) => point.periodEnd < day ? point.periodEnd : day, '9999-12-31');
    for (const archive of submissions.filings.files ?? []) {
      if (archive.filingTo < earliest || !/^CIK\d+-submissions-\d+\.json$/.test(archive.name)) continue;
      await new Promise(resolve => setTimeout(resolve, 300));
      const historical = await fetchSecJson<SecRecentFilings>(`https://data.sec.gov/submissions/${archive.name}`);
      filings.push(...listSecPeriodicFilings(historical));
    }
    const matched = matchCompanyReportSources(company, filings, cik);
    const merged = new Map((output[company.id] ?? []).map(reference => [reference.period, reference]));
    matched.forEach(reference => merged.set(reference.period, reference));
    output[company.id] = [...merged.values()].sort((a, b) => a.period.localeCompare(b.period));
    console.log(`${company.id}: ${matched.length} exact references, ${output[company.id].length} retained`);
  } catch (error) {
    failed = true;
    console.error(`${company.id}: ${String(error)}`);
  }
  await new Promise(resolve => setTimeout(resolve, 300));
}
if (args.has('--write') && !failed) {
  await writeFile('src/data/companyReportSources.sec.ts',
    '// Generated by npm run data:companies:sources -- --write.\n'
    + "import type { CompanyReportReference } from '../types';\n\n"
    + `export const secCompanyReportSources: Record<string, CompanyReportReference[]> = ${JSON.stringify(output, null, 2)};\n`);
} else if (failed) {
  console.error('Source index unchanged because one or more sources failed.');
  process.exitCode = 1;
}
