import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { companyFundamentalsDataset } from '../src/data/companyFundamentals';
import { listSecPeriodicFilings } from '../src/data/companyReportMaintenance';
import type {
  CompanyFundamentals,
  CompanyReportEvent,
} from '../src/types';
import {
  fetchSecSubmissions,
  loadSecCikByTicker,
  mapWithConcurrency,
  secArchiveUrl,
  secDomesticCompanies,
} from './lib/sec';

const args = new Set(process.argv.slice(2));
const yearArgument = [...args].find((argument) => argument.startsWith('--year='));
const year = Number(yearArgument?.slice('--year='.length) ?? new Date().getUTCFullYear());
const shouldWrite = args.has('--write');
const outputPath = resolve('src/data/companyReportCalendar.sec.ts');

if (!Number.isInteger(year) || year < 2000 || year > 2100) {
  throw new Error(`Invalid calendar year: ${yearArgument}`);
}

function reportPeriod(
  company: CompanyFundamentals,
  form: '10-Q' | '10-K',
  reportDate: string,
): string | undefined {
  const points = form === '10-K' ? company.annual : company.quarterly;
  const exact = points.find((point) => point.periodEnd === reportDate);
  if (exact) return exact.period;
  const reportTime = new Date(`${reportDate}T00:00:00Z`).getTime();
  const nearest = points
    .map((point) => ({
      point,
      days: Math.abs(
        new Date(`${point.periodEnd}T00:00:00Z`).getTime() - reportTime,
      ) / 86_400_000,
    }))
    .filter(({ days }) => days <= 7)
    .sort((left, right) => left.days - right.days)[0];
  return nearest?.point.period;
}

function generatedModule(events: readonly CompanyReportEvent[]): string {
  return `// Generated by npm run data:companies:calendar -- --year=${year} --write.\n`
    + `// Review pending filings before regenerating; do not edit this file manually.\n\n`
    + `import type { CompanyReportEvent } from '../types';\n\n`
    + `export const secCompanyReportEvents: CompanyReportEvent[] = ${JSON.stringify(events, null, 2)};\n`;
}

const cikByTicker = await loadSecCikByTicker();
const companies = secDomesticCompanies(companyFundamentalsDataset.companies);
const failures: string[] = [];
const pending: Array<{
  company: string;
  form: string;
  filedAt: string;
  reportDate: string;
  sourceUrl: string;
}> = [];

const eventGroups = await mapWithConcurrency(companies, 4, async (company) => {
  const cik = cikByTicker.get(company.ticker.toUpperCase());
  if (cik == null) {
    failures.push(`${company.name}: ticker ${company.ticker} not found`);
    return [];
  }
  try {
    const submissions = await fetchSecSubmissions(cik);
    return listSecPeriodicFilings(submissions.filings.recent, year).flatMap((filing) => {
      const period = reportPeriod(company, filing.form, filing.reportDate);
      const sourceUrl = secArchiveUrl(cik, filing);
      if (!period) {
        pending.push({
          company: company.name,
          form: filing.form,
          filedAt: filing.filingDate,
          reportDate: filing.reportDate,
          sourceUrl,
        });
        return [];
      }
      return [{
        companyId: company.id,
        period,
        publishedAt: filing.filingDate,
        status: 'reported' as const,
        sourceLabel: `${company.name} ${period} · SEC ${filing.form}`,
        sourceUrl,
      }];
    });
  } catch (error) {
    failures.push(`${company.name}: ${error instanceof Error ? error.message : String(error)}`);
    return [];
  }
});

const events = eventGroups.flat().sort((left, right) => (
  left.publishedAt.localeCompare(right.publishedAt)
    || left.companyId.localeCompare(right.companyId)
    || left.period.localeCompare(right.period)
));

if (shouldWrite) {
  await writeFile(outputPath, generatedModule(events), 'utf8');
  console.log(`Wrote ${events.length} SEC report events to ${outputPath}.`);
} else {
  console.log(JSON.stringify(events, null, 2));
}

if (pending.length > 0) {
  console.log('\nFilings not yet represented in the offline company dataset:');
  console.table(pending);
}
console.log(`${companies.length} companies checked; ${events.length} events; ${pending.length} pending; ${failures.length} failure(s).`);
if (failures.length > 0) {
  console.warn(failures.join('; '));
  process.exitCode = 1;
}
