// Generated by npm run data:companies:calendar -- --year=2026 --write.
// Review pending filings before regenerating; do not edit this file manually.

import type { CompanyReportEvent } from '../types';

export const secCompanyReportEvents: CompanyReportEvent[] = [
  {
    "companyId": "adbe",
    "period": "FY2025",
    "publishedAt": "2026-01-15",
    "status": "reported",
    "sourceLabel": "Adobe FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/796343/000079634326000003/adbe-20251128.htm"
  },
  {
    "companyId": "intel",
    "period": "FY2025",
    "publishedAt": "2026-01-23",
    "status": "reported",
    "sourceLabel": "英特尔 FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/50863/000005086326000011/intc-20251227.htm"
  },
  {
    "companyId": "microsoft",
    "period": "FY2026 Q2",
    "publishedAt": "2026-01-28",
    "status": "reported",
    "sourceLabel": "微软 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/789019/000119312526027207/msft-20251231.htm"
  },
  {
    "companyId": "meta",
    "period": "FY2025",
    "publishedAt": "2026-01-29",
    "status": "reported",
    "sourceLabel": "Meta FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1326801/000162828026003942/meta-20251231.htm"
  },
  {
    "companyId": "tesla",
    "period": "FY2025",
    "publishedAt": "2026-01-29",
    "status": "reported",
    "sourceLabel": "特斯拉 FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1318605/000162828026003952/tsla-20251231.htm"
  },
  {
    "companyId": "apple",
    "period": "FY2026 Q1",
    "publishedAt": "2026-01-30",
    "status": "reported",
    "sourceLabel": "苹果 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/320193/000032019326000006/aapl-20251227.htm"
  },
  {
    "companyId": "visa",
    "period": "FY2026 Q1",
    "publishedAt": "2026-01-30",
    "status": "reported",
    "sourceLabel": "Visa FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1403161/000140316126000045/v-20251231.htm"
  },
  {
    "companyId": "amd",
    "period": "FY2025",
    "publishedAt": "2026-02-04",
    "status": "reported",
    "sourceLabel": "AMD FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/2488/000000248826000018/amd-20251227.htm"
  },
  {
    "companyId": "qualcomm",
    "period": "FY2026 Q1",
    "publishedAt": "2026-02-04",
    "status": "reported",
    "sourceLabel": "高通 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/804328/000080432826000017/qcom-20251228.htm"
  },
  {
    "companyId": "alphabet",
    "period": "FY2025",
    "publishedAt": "2026-02-05",
    "status": "reported",
    "sourceLabel": "谷歌 FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1652044/000165204426000018/goog-20251231.htm"
  },
  {
    "companyId": "amazon",
    "period": "FY2025",
    "publishedAt": "2026-02-06",
    "status": "reported",
    "sourceLabel": "亚马逊 FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1018724/000101872426000004/amzn-20251231.htm"
  },
  {
    "companyId": "txn",
    "period": "FY2025",
    "publishedAt": "2026-02-06",
    "status": "reported",
    "sourceLabel": "德州仪器 FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/97476/000009747626000059/txn-20251231.htm"
  },
  {
    "companyId": "jnj",
    "period": "FY2025",
    "publishedAt": "2026-02-11",
    "status": "reported",
    "sourceLabel": "强生 FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/200406/000020040626000016/jnj-20251228.htm"
  },
  {
    "companyId": "lilly",
    "period": "FY2025",
    "publishedAt": "2026-02-12",
    "status": "reported",
    "sourceLabel": "礼来 FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/59478/000005947826000013/lly-20251231.htm"
  },
  {
    "companyId": "cisco",
    "period": "FY2026 Q2",
    "publishedAt": "2026-02-17",
    "status": "reported",
    "sourceLabel": "思科 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/858877/000085887726000021/csco-20260124.htm"
  },
  {
    "companyId": "palantir",
    "period": "FY2025",
    "publishedAt": "2026-02-17",
    "status": "reported",
    "sourceLabel": "Palantir FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1321655/000132165526000011/pltr-20251231.htm"
  },
  {
    "companyId": "appliedMaterials",
    "period": "FY2026 Q1",
    "publishedAt": "2026-02-19",
    "status": "reported",
    "sourceLabel": "应用材料 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/6951/000162828026009694/amat-20260125.htm"
  },
  {
    "companyId": "ibm",
    "period": "FY2025",
    "publishedAt": "2026-02-24",
    "status": "reported",
    "sourceLabel": "IBM FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/51143/000005114326000010/ibm-20251231.htm"
  },
  {
    "companyId": "merck",
    "period": "FY2025",
    "publishedAt": "2026-02-24",
    "status": "reported",
    "sourceLabel": "默沙东 FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/310158/000031015826000063/mrk-20251231.htm"
  },
  {
    "companyId": "nvidia",
    "period": "FY2026",
    "publishedAt": "2026-02-25",
    "status": "reported",
    "sourceLabel": "英伟达 FY2026 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000021/nvda-20260125.htm"
  },
  {
    "companyId": "pfizer",
    "period": "FY2025",
    "publishedAt": "2026-02-26",
    "status": "reported",
    "sourceLabel": "辉瑞 FY2025 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/78003/000007800326000026/pfe-20251231.htm"
  },
  {
    "companyId": "crm",
    "period": "FY2026",
    "publishedAt": "2026-03-02",
    "status": "reported",
    "sourceLabel": "Salesforce FY2026 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1108524/000110852426000060/crm-20260131.htm"
  },
  {
    "companyId": "broadcom",
    "period": "FY2026 Q1",
    "publishedAt": "2026-03-11",
    "status": "reported",
    "sourceLabel": "博通 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1730168/000173016826000016/avgo-20260201.htm"
  },
  {
    "companyId": "oracle",
    "period": "FY2026 Q3",
    "publishedAt": "2026-03-11",
    "status": "reported",
    "sourceLabel": "甲骨文 FY2026 Q3 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1341439/000119312526101045/orcl-20260228.htm"
  },
  {
    "companyId": "walmart",
    "period": "FY2026",
    "publishedAt": "2026-03-13",
    "status": "reported",
    "sourceLabel": "沃尔玛 FY2026 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/104169/000010416926000055/wmt-20260131.htm"
  },
  {
    "companyId": "micron",
    "period": "FY2026 Q2",
    "publishedAt": "2026-03-19",
    "status": "reported",
    "sourceLabel": "美光 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/723125/000072312526000006/mu-20260226.htm"
  },
  {
    "companyId": "adbe",
    "period": "FY2026 Q1",
    "publishedAt": "2026-03-25",
    "status": "reported",
    "sourceLabel": "Adobe FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/796343/000079634326000056/adbe-20260227.htm"
  },
  {
    "companyId": "jnj",
    "period": "FY2026 Q1",
    "publishedAt": "2026-04-22",
    "status": "reported",
    "sourceLabel": "强生 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/200406/000020040626000087/jnj-20260329.htm"
  },
  {
    "companyId": "ibm",
    "period": "FY2026 Q1",
    "publishedAt": "2026-04-23",
    "status": "reported",
    "sourceLabel": "IBM FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/51143/000005114326000038/ibm-20260331.htm"
  },
  {
    "companyId": "tesla",
    "period": "FY2026 Q1",
    "publishedAt": "2026-04-23",
    "status": "reported",
    "sourceLabel": "特斯拉 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1318605/000162828026026673/tsla-20260331.htm"
  },
  {
    "companyId": "intel",
    "period": "FY2026 Q1",
    "publishedAt": "2026-04-24",
    "status": "reported",
    "sourceLabel": "英特尔 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/50863/000005086326000079/intc-20260328.htm"
  },
  {
    "companyId": "txn",
    "period": "FY2026 Q1",
    "publishedAt": "2026-04-24",
    "status": "reported",
    "sourceLabel": "德州仪器 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/97476/000009747626000101/txn-20260331.htm"
  },
  {
    "companyId": "microsoft",
    "period": "FY2026 Q3",
    "publishedAt": "2026-04-29",
    "status": "reported",
    "sourceLabel": "微软 FY2026 Q3 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/789019/000119312526191507/msft-20260331.htm"
  },
  {
    "companyId": "qualcomm",
    "period": "FY2026 Q2",
    "publishedAt": "2026-04-29",
    "status": "reported",
    "sourceLabel": "高通 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/804328/000080432826000061/qcom-20260329.htm"
  },
  {
    "companyId": "visa",
    "period": "FY2026 Q2",
    "publishedAt": "2026-04-29",
    "status": "reported",
    "sourceLabel": "Visa FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1403161/000140316126000079/v-20260331.htm"
  },
  {
    "companyId": "alphabet",
    "period": "FY2026 Q1",
    "publishedAt": "2026-04-30",
    "status": "reported",
    "sourceLabel": "谷歌 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1652044/000165204426000048/goog-20260331.htm"
  },
  {
    "companyId": "amazon",
    "period": "FY2026 Q1",
    "publishedAt": "2026-04-30",
    "status": "reported",
    "sourceLabel": "亚马逊 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1018724/000101872426000014/amzn-20260331.htm"
  },
  {
    "companyId": "lilly",
    "period": "FY2026 Q1",
    "publishedAt": "2026-04-30",
    "status": "reported",
    "sourceLabel": "礼来 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/59478/000005947826000045/lly-20260331.htm"
  },
  {
    "companyId": "meta",
    "period": "FY2026 Q1",
    "publishedAt": "2026-04-30",
    "status": "reported",
    "sourceLabel": "Meta FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1326801/000162828026028526/meta-20260331.htm"
  },
  {
    "companyId": "apple",
    "period": "FY2026 Q2",
    "publishedAt": "2026-05-01",
    "status": "reported",
    "sourceLabel": "苹果 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/320193/000032019326000013/aapl-20260328.htm"
  },
  {
    "companyId": "merck",
    "period": "FY2026 Q1",
    "publishedAt": "2026-05-04",
    "status": "reported",
    "sourceLabel": "默沙东 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/310158/000162828026029802/mrk-20260331.htm"
  },
  {
    "companyId": "palantir",
    "period": "FY2026 Q1",
    "publishedAt": "2026-05-05",
    "status": "reported",
    "sourceLabel": "Palantir FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1321655/000132165526000028/pltr-20260331.htm"
  },
  {
    "companyId": "pfizer",
    "period": "FY2026 Q1",
    "publishedAt": "2026-05-05",
    "status": "reported",
    "sourceLabel": "辉瑞 FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/78003/000007800326000054/pfe-20260329.htm"
  },
  {
    "companyId": "amd",
    "period": "FY2026 Q1",
    "publishedAt": "2026-05-06",
    "status": "reported",
    "sourceLabel": "AMD FY2026 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/2488/000000248826000076/amd-20260328.htm"
  },
  {
    "companyId": "cisco",
    "period": "FY2026 Q3",
    "publishedAt": "2026-05-19",
    "status": "reported",
    "sourceLabel": "思科 FY2026 Q3 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/858877/000085887726000078/csco-20260425.htm"
  },
  {
    "companyId": "nvidia",
    "period": "FY2027 Q1",
    "publishedAt": "2026-05-20",
    "status": "reported",
    "sourceLabel": "英伟达 FY2027 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000052/nvda-20260426.htm"
  },
  {
    "companyId": "appliedMaterials",
    "period": "FY2026 Q2",
    "publishedAt": "2026-05-21",
    "status": "reported",
    "sourceLabel": "应用材料 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/6951/000162828026037227/amat-20260426.htm"
  },
  {
    "companyId": "crm",
    "period": "FY2027 Q1",
    "publishedAt": "2026-05-28",
    "status": "reported",
    "sourceLabel": "Salesforce FY2027 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1108524/000110852426000127/crm-20260430.htm"
  },
  {
    "companyId": "walmart",
    "period": "FY2027 Q1",
    "publishedAt": "2026-05-29",
    "status": "reported",
    "sourceLabel": "沃尔玛 FY2027 Q1 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/104169/000010416926000102/wmt-20260430.htm"
  },
  {
    "companyId": "broadcom",
    "period": "FY2026 Q2",
    "publishedAt": "2026-06-09",
    "status": "reported",
    "sourceLabel": "博通 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1730168/000173016826000054/avgo-20260503.htm"
  },
  {
    "companyId": "adbe",
    "period": "FY2026 Q2",
    "publishedAt": "2026-06-15",
    "status": "reported",
    "sourceLabel": "Adobe FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/796343/000079634326000112/adbe-20260529.htm"
  },
  {
    "companyId": "oracle",
    "period": "FY2026",
    "publishedAt": "2026-06-22",
    "status": "reported",
    "sourceLabel": "甲骨文 FY2026 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1341439/000119312526277521/orcl-20260531.htm"
  },
  {
    "companyId": "micron",
    "period": "FY2026 Q3",
    "publishedAt": "2026-06-25",
    "status": "reported",
    "sourceLabel": "美光 FY2026 Q3 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/723125/000072312526000015/mu-20260528.htm"
  },
  {
    "companyId": "alphabet",
    "period": "FY2026 Q2",
    "publishedAt": "2026-07-23",
    "status": "reported",
    "sourceLabel": "谷歌 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1652044/000165204426000071/goog-20260630.htm"
  },
  {
    "companyId": "ibm",
    "period": "FY2026 Q2",
    "publishedAt": "2026-07-23",
    "status": "reported",
    "sourceLabel": "IBM FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/51143/000005114326000078/ibm-20260630.htm"
  },
  {
    "companyId": "jnj",
    "period": "FY2026 Q2",
    "publishedAt": "2026-07-23",
    "status": "reported",
    "sourceLabel": "强生 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/200406/000020040626000153/jnj-20260628.htm"
  },
  {
    "companyId": "tesla",
    "period": "FY2026 Q2",
    "publishedAt": "2026-07-23",
    "status": "reported",
    "sourceLabel": "特斯拉 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1318605/000162828026049270/tsla-20260630.htm"
  },
  {
    "companyId": "intel",
    "period": "FY2026 Q2",
    "publishedAt": "2026-07-24",
    "status": "reported",
    "sourceLabel": "英特尔 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/50863/000005086326000157/intc-20260627.htm"
  },
  {
    "companyId": "txn",
    "period": "FY2026 Q2",
    "publishedAt": "2026-07-24",
    "status": "reported",
    "sourceLabel": "德州仪器 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/97476/000009747626000152/txn-20260630.htm"
  },
  {
    "companyId": "microsoft",
    "period": "FY2026",
    "publishedAt": "2026-07-29",
    "status": "reported",
    "sourceLabel": "微软 FY2026 · SEC 10-K",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/789019/000119312526323660/msft-20260630.htm"
  },
  {
    "companyId": "qualcomm",
    "period": "FY2026 Q3",
    "publishedAt": "2026-07-29",
    "status": "reported",
    "sourceLabel": "高通 FY2026 Q3 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/804328/000080432826000086/qcom-20260628.htm"
  },
  {
    "companyId": "visa",
    "period": "FY2026 Q3",
    "publishedAt": "2026-07-29",
    "status": "reported",
    "sourceLabel": "Visa FY2026 Q3 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1403161/000140316126000104/v-20260630.htm"
  },
  {
    "companyId": "meta",
    "period": "FY2026 Q2",
    "publishedAt": "2026-07-30",
    "status": "reported",
    "sourceLabel": "Meta FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1326801/000162828026050705/meta-20260630.htm"
  },
  {
    "companyId": "amazon",
    "period": "FY2026 Q2",
    "publishedAt": "2026-07-31",
    "status": "reported",
    "sourceLabel": "亚马逊 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1018724/000101872426000026/amzn-20260630.htm"
  },
  {
    "companyId": "apple",
    "period": "FY2026 Q3",
    "publishedAt": "2026-07-31",
    "status": "reported",
    "sourceLabel": "苹果 FY2026 Q3 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/320193/000032019326000020/aapl-20260627.htm"
  },
  {
    "companyId": "palantir",
    "period": "FY2026 Q2",
    "publishedAt": "2026-08-04",
    "status": "reported",
    "sourceLabel": "Palantir FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1321655/000132165526000041/pltr-20260630.htm"
  },
  {
    "companyId": "pfizer",
    "period": "FY2026 Q2",
    "publishedAt": "2026-08-04",
    "status": "reported",
    "sourceLabel": "辉瑞 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/78003/000007800326000095/pfe-20260628.htm"
  },
  {
    "companyId": "amd",
    "period": "FY2026 Q2",
    "publishedAt": "2026-08-05",
    "status": "reported",
    "sourceLabel": "AMD FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/2488/000000248826000123/amd-20260627.htm"
  },
  {
    "companyId": "lilly",
    "period": "FY2026 Q2",
    "publishedAt": "2026-08-05",
    "status": "reported",
    "sourceLabel": "礼来 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/59478/000005947826000081/lly-20260630.htm"
  },
  {
    "companyId": "merck",
    "period": "FY2026 Q2",
    "publishedAt": "2026-08-07",
    "status": "reported",
    "sourceLabel": "默沙东 FY2026 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/310158/000031015826000212/mrk-20260630.htm"
  },
  {
    "companyId": "appliedMaterials",
    "period": "FY2026 Q3",
    "publishedAt": "2026-08-20",
    "status": "reported",
    "sourceLabel": "应用材料 FY2026 Q3 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/6951/000162828026058235/amat-20260726.htm"
  },
  {
    "companyId": "nvidia",
    "period": "FY2027 Q2",
    "publishedAt": "2026-08-26",
    "status": "reported",
    "sourceLabel": "英伟达 FY2027 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000075/nvda-20260726.htm"
  },
  {
    "companyId": "crm",
    "period": "FY2027 Q2",
    "publishedAt": "2026-08-27",
    "status": "reported",
    "sourceLabel": "Salesforce FY2027 Q2 · SEC 10-Q",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1108524/000110852426000190/crm-20260731.htm"
  }
];
